# Generated by Django 4.2.14 on 2024-07-24 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truckregistration',
            name='year',
            field=models.PositiveIntegerField(),
        ),
    ]
