# Generated by Django 4.2.14 on 2024-07-24 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_alter_driver_experience_months_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='driver_type',
        ),
    ]
