# Generated by Django 4.2.14 on 2024-07-24 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_remove_driver_driver_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='truck_status',
            field=models.CharField(choices=[('Owner Operator', 'Owner Operator'), ('Company Driver', 'Company Driver'), ('Lease Operator', 'Lease Operator')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
