# Generated by Django 4.2.14 on 2024-07-25 22:22

from django.db import migrations, models
import django.db.models.deletion

def create_default_simcard(apps, schema_editor):
    SimCard = apps.get_model('tablets', 'SimCard')
    default_simcard = SimCard.objects.create(name='Default SIM', sim_card_number='0000000000')
    Tablet = apps.get_model('tablets', 'Tablet')
    for tablet in Tablet.objects.all():
        tablet.sim_card = default_simcard
        tablet.save()

class Migration(migrations.Migration):

    dependencies = [
        ('tablets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('sim_card_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='tablet',
            name='sim_card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tablets', to='tablets.simcard'),
        ),
        migrations.RunPython(create_default_simcard),
        migrations.AlterField(
            model_name='tablet',
            name='sim_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tablets', to='tablets.simcard'),
        ),
    ]
