# Generated by Django 4.2.14 on 2024-07-28 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tablets', '0002_simcard_remove_tablet_sim_card_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablet',
            name='sim_card_number',
        ),
    ]
