# Generated by Django 4.2.14 on 2024-07-23 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fuel_cards', '0001_initial'),
        ('transponders', '__first__'),
        ('drivers', '0001_initial'),
        ('tablets', '__first__'),
        ('trucks', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fleetbox',
            fields=[
                ('fleet_box_id', models.AutoField(primary_key=True, serialize=False)),
                ('assigned_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drivers_assigned', to='drivers.driver')),
                ('assigned_driver_co_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drivers_assigned_co_driver', to='drivers.driver')),
                ('assigned_fuel_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drivers_assigned_fuel_card_number', to='fuel_cards.fuelcard', to_field='number')),
                ('assigned_tablet_imei', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drivers_assigned_tablet_sim', to='tablets.tablet', to_field='imei')),
                ('assigned_transponder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drivers_assigned_transponder_number', to='transponders.transponder', to_field='number')),
                ('assigned_truck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drivers_assigned_vin', to='trucks.truckregistration', to_field='vin')),
            ],
        ),
    ]
