# Generated by Django 4.2.14 on 2024-07-28 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('driver_name', models.CharField(blank=True, max_length=255, null=True)),
                ('dispatcher_name', models.CharField(blank=True, max_length=255, null=True)),
                ('broker_name', models.CharField(blank=True, max_length=255, null=True)),
                ('load_id', models.CharField(blank=True, max_length=50, null=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('load_status', models.CharField(choices=[('dispatched', 'dispatched'), ('in transit', 'In Transit'), ('delivered', 'delivered'), ('cancelled', 'cancelled')], max_length=50)),
                ('broker_pay', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('driver_pay', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TripLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_type', models.CharField(choices=[('pickup', 'Pickup'), ('delivery', 'Delivery')], max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('sequence', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='trips.trip')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
    ]
